server:
  port: 8082

spring:
  application:
    name: animal-service
  datasource:
    url: jdbc:postgresql://localhost:5432/vetmngsys_animal_db
    username: canberk
    password: bancerk
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      '[hibernate.format_sql]': true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}